FROM php:8.0-fpm

COPY --from=composer:2.0 /usr/bin/composer /usr/bin/composer

RUN apt-get update && \
    apt-get -y install \
    git \
    zip \
    unzip \
    vim \
    && docker-php-ext-install pdo_mysql bcmath

COPY ./docker/php/php.ini /usr/local/etc/php/php.ini
COPY ./api /var/www/html

WORKDIR /var/www/html

RUN composer install && \
		php artisan cache:clear && \
		php artisan config:clear && \
		chmod -R 777 storage
