version: 2.1

executors:
  deploy:
    docker:
      - image: cimg/php:8.0.13
        # environment:
        #   APP_ENV: testing
        #   DB_CONNECTION: mysql
        #   DB_HOST: 127.0.0.1
        #   DB_DATABASE: testing
        #   DB_USERNAME: 'root'
        #   DB_PASSWORD: ''
      # - image: circleci/mysql:8
      #   environment:
      #     MYSQL_DATABASE: testing
      #     MYSQL_ROOT_HOST: '%'
      #     MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      #     TZ: Asia/Tokyo
      #   command: [--platform linux/amd64]

    working_directory: ~/repo

commands:
  backend_test:
    steps:
      - checkout

      # restore gem from cache
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "~/repo/api/composer.lock" }}
            - composer-v1-
          working_directory: ~/repo/api

      - run:
          command: composer install -n --prefer-dist
          working_directory: ~/repo/api

      - save_cache:
          key: composer-v1-{{ checksum "~/repo/api/composer.lock" }}
          paths:
            - ~/repo/api/vendor
          working_directory: ~/repo/api

      # Database setup
      # - run:
      #     command: php artisan migrate --force
      #     working_directory: ~/repo/api

      # run tests
      - run:
          name: php test
          command: vendor/bin/phpunit
          working_directory: ~/repo/api

jobs:
  backend_test:
    executor: deploy
    steps:
      # - checkout
      - backend_test

workflows:
  push-branch-workflow:
    jobs:
      - backend_test:
          name: "backend_test"
# workflows:
#   version: 2
#   test:
#     jobs:
#       - test_backend:
          # filters:
          #   branches:
          #     ignore: main
