FROM nginx:1.18-alpine

ENV TZ Asia/Tokyo
EXPOSE 80

COPY ./docker/nginx/prod/default.conf /etc/nginx/conf.d/default.conf
COPY ./docker/nginx/prod/nginx.conf /etc/nginx/nginx.conf
COPY ./api /var/www/html

CMD ["nginx", "-g", "daemon off;"]

WORKDIR /var/www/html

